version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - ${WEB_HOST_PORT}:${WEB_CONTAINER_PORT}
    depends_on:
      - db
      - cache
    volumes:
      - ./config/config.json:/app/config/config.json
  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:6.2-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
